#平台Id;值为1至14;15固定为给开发商
defaultDeptId = 21

#服务器Id(最大数字14000)
serverId=1

#是否开启GM工具
opengmtools=1

#是否本地登入
isLocalLogin=1

#是否打开防火墙
openFireWall=0

#运行类型;t:测试服;s：生产服
runType=s


devMode =true


#国际化资源定义:
#zh_CN:简体中文
#en_US:英语
#zh_TW:繁体中文(台湾）
#zh_HK:繁体中文(香港)
i18n =zh_CN
