httpServerPort = 39001

#调试状态;1:调试状态;0:生产状态;
debug=0

#密钥
chargeserver.my=chargeserver8888miyao

#运营商ID
deptId=21

servlet=com.luoshenfu.support.charge.UserChargeServlet,com.luoshenfu.support.charge.TestServlet,com.luoshenfu.support.charge.UserInfoQueryServlet,com.luoshenfu.support.charge.UserTencentChargeServlet
#ip白名单
chargeIp=127.0.0.1,127.0.0.1
