dbType=mysql
driverClassName=com.mysql.jdbc.Driver
minIdle=1
maxActive=1
initialSize=1
removeAbandoned=true
removeAbandonedTimeout=600
logAbandoned=true
validationQuery=select 1
testWhileIdle=true
jndi-name=/crossDataDb
filters=stat
