dbType=mysql
driverClassName=com.mysql.jdbc.Driver
url=jdbc\:mysql\://127.0.0.1\:3306/smzt_game_s1?autoReconnect\=true&amp;useUnicode\=true&amp;characterEncoding\=UTF-8&amp;useSSL=false
username=root
password=123456
maxWait=600000
maxActive=1000
initialSize=200
removeAbandoned=true
removeAbandonedTimeout=1200
logAbandoned=true
validationQuery=select 1
testWhileIdle=true
timeBetweenEvictionRunsMillis=600000
minEvictableIdleTimeMillis=3000000
filters=stat


