dbType=mysql
driverClassName=com.mysql.jdbc.Driver
url=jdbc\:mysql\://127.0.0.1\:3306/smzt_datacenter?autoReconnect\=true&amp;useUnicode\=true&amp;characterEncoding\=UTF-8&amp;useSSL=true
username=root
password=123456
minIdle=1
maxActive=50
initialSize=3
removeAbandoned=true
removeAbandonedTimeout=600
logAbandoned=true
validationQuery=select 1
testWhileIdle=true
